### ISSUE TITLE
Cannot download the model

### ISSUE THREAD

**Issue by askonivala** [qurator-spk/sbb_ner#1]
For some reason I am not able to download the model from your server. I got "Network is unreachable." error with multiple tries.

**Comment by cneud** [comment]
Dear @askonivala, apologies but unfortunately our IT has taken down for good the fileserver where the models were hosted...we're currently investigating alternative hosting options and hope to come up with a stopgap solution over the next couple of days!

**Comment by labusch** [comment]
Dear  @askonivala, 
we finally managed to set up a new storage location for our models. 
Please use the new download link in order to get the models.
