### ISSUE TITLE
explanation of prediction

### ISSUE THREAD

**Issue by Ashbajawed** [qurator-spk/sbb_ner#3]
can you provide a bit detial or explanation of prediction especially of the following  words/Alphabets
{'B-LOC', 'B-ORG', 'B-PER', 'I-ORG', 'I-PER', 'O'}

**Comment by mikegerber** [comment]
Those are the quasi-standard NER tags used everywhere. I found a good explanation here:

https://estnltk.github.io/estnltk/1.4.1/tutorials/ner.html
> The default models use tags PER, ORG and LOC to denote person names, organizations and locations respectively. Entity tags are encoded using a BIO annotation scheme, where each entity label is prefixed with either B or I letter. B- denotes the beginning and I- inside of an entity. The prefixes are used to detect multiword entities, as shown in the example example above. All other words, which don’t refer to entities of interest, are labelled with the O tag.
